# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: false
os:
  - linux
  # - osx  # we don't do any binary dependencies or OS specific magic
julia:
  - 0.5
  - 0.6
notifications:
  email: false
# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("Starboxes"); Pkg.test("Starboxes"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("Starboxes")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("Starboxes")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
